 CREATE TRIGGER cron_job_cache_invalidate AFTER INSERT OR DELETE OR UPDATE OR TRUNCATE ON cron.job FOR EACH STATEMENT EXECUTE FUNCTION cron.job_cache_invalidate();
 CREATE TRIGGER generate_certificate_path_trigger BEFORE INSERT ON public.certificates FOR EACH ROW EXECUTE FUNCTION trigger_generate_certificate_path();
 CREATE TRIGGER handle_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
 CREATE TRIGGER log_certificate_activity AFTER INSERT ON public.certificates FOR EACH ROW EXECUTE FUNCTION log_user_activity();
 CREATE TRIGGER log_test_completion_activity AFTER UPDATE ON public.test_attempts FOR EACH ROW WHEN (((old.status <> 'submitted'::text) AND (new.status = 'submitted'::text))) EXECUTE FUNCTION log_user_activity();
 CREATE TRIGGER log_test_registration_activity AFTER INSERT ON public.test_registrations FOR EACH ROW EXECUTE FUNCTION log_user_activity();
 CREATE TRIGGER recalculate_ranks_trigger AFTER UPDATE ON public.user_points FOR EACH ROW EXECUTE FUNCTION trigger_recalculate_ranks();
 CREATE TRIGGER sync_test_registrations_profile_trigger BEFORE INSERT OR UPDATE ON public.test_registrations FOR EACH ROW EXECUTE FUNCTION sync_test_registrations_profile_data();
 CREATE TRIGGER track_event_registration_analytics AFTER INSERT OR DELETE ON public.event_registrations FOR EACH ROW EXECUTE FUNCTION track_event_registration();
 CREATE TRIGGER track_hackathon_registration_analytics AFTER INSERT OR DELETE ON public.hackathon_registrations FOR EACH ROW EXECUTE FUNCTION track_event_registration();
 CREATE TRIGGER trg_set_profile_email BEFORE INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION set_profile_email();
 CREATE TRIGGER trg_sync_names_insert_interns BEFORE INSERT ON public.interns FOR EACH ROW EXECUTE FUNCTION sync_intern_names();
 CREATE TRIGGER trg_sync_names_update_profiles AFTER UPDATE OF first_name, last_name ON public.profiles FOR EACH ROW EXECUTE FUNCTION sync_intern_names();
 CREATE TRIGGER trigger_auto_generate_codeunia_id BEFORE INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION auto_generate_codeunia_id();
 CREATE TRIGGER trigger_log_event_creation AFTER INSERT ON public.events FOR EACH ROW EXECUTE FUNCTION log_event_creation();
 CREATE TRIGGER trigger_log_event_deletion BEFORE DELETE ON public.events FOR EACH ROW EXECUTE FUNCTION log_event_deletion();
 CREATE TRIGGER trigger_notify_company_rejected AFTER UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION notify_company_rejected();
 CREATE TRIGGER trigger_notify_company_verified AFTER UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION notify_company_verified();
 CREATE TRIGGER trigger_notify_event_approved AFTER UPDATE OF approval_status ON public.events FOR EACH ROW WHEN (((new.approval_status = 'approved'::text) AND (old.approval_status IS DISTINCT FROM 'approved'::text))) EXECUTE FUNCTION notify_event_approved();
 CREATE TRIGGER trigger_notify_event_changes_requested AFTER UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION notify_event_changes_requested();
 CREATE TRIGGER trigger_notify_event_rejected AFTER UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION notify_event_rejected();
 CREATE TRIGGER trigger_notify_hackathon_approved AFTER UPDATE ON public.hackathons FOR EACH ROW EXECUTE FUNCTION notify_hackathon_approved();
 CREATE TRIGGER trigger_process_organization_data BEFORE INSERT OR UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION process_organization_data();
 CREATE TRIGGER trigger_update_company_events_count AFTER INSERT OR DELETE OR UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION update_company_events_count();
 CREATE TRIGGER trigger_update_company_hackathons_count AFTER INSERT OR DELETE OR UPDATE ON public.hackathons FOR EACH ROW EXECUTE FUNCTION update_company_hackathons_count();
 CREATE TRIGGER trigger_update_conversation_last_message AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION update_conversation_last_message();
 CREATE TRIGGER trigger_update_event_registration_count AFTER INSERT OR DELETE OR UPDATE ON public.master_registrations FOR EACH ROW EXECUTE FUNCTION update_event_registration_count();
 CREATE TRIGGER trigger_update_hackathon_registration_count AFTER INSERT OR DELETE OR UPDATE ON public.master_registrations FOR EACH ROW EXECUTE FUNCTION update_hackathon_registration_count();
 CREATE TRIGGER update_ai_training_data_updated_at BEFORE UPDATE ON public.ai_training_data FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_company_members_updated_at BEFORE UPDATE ON public.company_members FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_company_registrations_on_event_change AFTER INSERT OR DELETE OR UPDATE OF registered, company_id ON public.events FOR EACH ROW EXECUTE FUNCTION trigger_update_company_registrations_from_events();
 CREATE TRIGGER update_company_registrations_on_hackathon_change AFTER INSERT OR DELETE OR UPDATE OF registered, company_id ON public.hackathons FOR EACH ROW EXECUTE FUNCTION trigger_update_company_registrations_from_hackathons();
 CREATE TRIGGER update_company_stats_on_event AFTER INSERT OR DELETE ON public.events FOR EACH ROW EXECUTE FUNCTION update_company_statistics();
 CREATE TRIGGER update_company_stats_on_hackathon AFTER INSERT OR DELETE ON public.hackathons FOR EACH ROW EXECUTE FUNCTION update_company_statistics();
 CREATE TRIGGER update_contact_submissions_updated_at BEFORE UPDATE ON public.contact_submissions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_core_team_applications_updated_at BEFORE UPDATE ON public.core_team_applications FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_event_registrations_updated_at BEFORE UPDATE ON public.event_registrations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_events_updated_at BEFORE UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_hackathon_registrations_updated_at BEFORE UPDATE ON public.hackathon_registrations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_notifications_updated_at BEFORE UPDATE ON public.notifications FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_payments_updated_at BEFORE UPDATE ON public.payments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_resumes_updated_at BEFORE UPDATE ON public.resumes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_round_registrations_updated_at BEFORE UPDATE ON public.round_registrations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_support_tickets_updated_at_trigger BEFORE UPDATE ON public.support_tickets FOR EACH ROW EXECUTE FUNCTION update_support_tickets_updated_at();
 CREATE TRIGGER update_test_rounds_updated_at BEFORE UPDATE ON public.test_rounds FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
 CREATE TRIGGER update_user_presence_updated_at_trigger BEFORE UPDATE ON public.user_presence FOR EACH ROW EXECUTE FUNCTION update_user_presence_updated_at();

