"use client"
import Footer from "@/components/footer";
import Header from "@/components/header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"
import {
  Shield,
  FileText,
  Mail,
  AlertTriangle,
  CheckCircle,
  Calendar,
  BookOpen,
  User,
  Database,
  Globe,
} from "lucide-react"
import { motion } from "framer-motion"

export default function PrivacyPage() {
  const lastUpdated = "July 27, 2025"
  // Define content structure with potential bullet points
  const sections = [
    {
      id: "introduction",
      title: "Introduction",
      icon: BookOpen,
      content: [
        {
          subtitle: "Overview",
          description:
            "The Codeunia services, including its community platform, courses, content, mentoring services, events, training platforms, and products such as BuildUnia (collectively, the &quot;Services&quot;), are provided through our website <a href=\"https://codeunia.com\" className=\"text-blue-500 hover:underline\">https://codeunia.com</a> (and its subdomains like <a href=\"https://buildunia.codeunia.com\" className=\"text-blue-500 hover:underline\">https://buildunia.codeunia.com</a>), and applications (collectively, the &quot;Platform&quot;), operated by Codeunia, a sole proprietorship registered in India under the ownership of Deepak (&quot;us,&quot; &quot;we,&quot; or &quot;the Company&quot;). In connection with your use of the Services, we may collect/receive, store, use, share, and/or process certain information (&quot;Information&quot;) about you when you use our Services. By using the Services, you agree to the collection and use of Information in accordance with this Privacy Policy.",
          bullets: []
        },
        {
          subtitle: "Definitions",
          description: "",
          bullets: [
            "<strong>Service(s)</strong>: Codeunia platform and its products, including BuildUnia, courses, content, instructor support, training platforms, and activities.",
            "<strong>Platform</strong>: Our websites (e.g., <a href=\"https://codeunia.com\" className=\"text-blue-500 hover:underline\">codeunia.com</a>, <a href=\"https://buildunia.codeunia.com\" className=\"text-blue-500 hover:underline\">buildunia.codeunia.com</a>), applications, WhatsApp groups, Facebook groups, and social media presence.",
            "<strong>Information</strong>: Any data we collect, receive, store, use, share, and/or process about you in connection with your use of the Services, including Personal Information, Usage Data, and Sensitive Personal Information.",
            "<strong>Personal Information</strong>: Any information that relates to an identified or identifiable individual.",
            "<strong>Usage Data</strong>: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
            "<strong>Sensitive Personal Information</strong>: Passwords and any other information classified as sensitive under Indian law."
          ]
        }
      ],
    },
    {
      id: "information-collection",
      title: "Information Collection",
      icon: Database,
      content: [
        {
          subtitle: "Personal Information",
          description: "We may ask you to provide us with certain personally identifiable Information that can be used to contact or identify you.",
          bullets: [
            "Your name, email address, phone number",
            "Your Account Data (profile, courses/projects opted, mentoring sessions booked, etc.)",
            "User Content shared via your Account",
            "Linked account data",
            "Promotions and survey data",
            "Support concerns (internal use)",
            "Device information",
            "Parts of our Services you use"
          ]
        },
        {
          subtitle: "Usage Data (Log Data)",
          description: "We may also collect Information that your browser sends whenever you visit our Platform (&quot;Log Data&quot;).",
          bullets: [
            "IP address, browser type/version, device type",
            "Pages visited, time/date, time spent, statistics",
            "Approximate geographic location"
          ]
        },
        {
          subtitle: "Financial Information",
          description: "To receive payments for Services, we may collect (directly or via payment partners) certain financial Information as required.",
          bullets: []
        },
        {
          subtitle: "Third-Party Technologies",
          description: "",
          bullets: [
            "<strong>Cookies</strong>: Used for personalization, login, analytics. You may refuse cookies, but some features may not work.",
            "<strong>Analytics</strong>: We use Google Analytics and similar services to analyze usage and improve our Services. You can opt out via browser add-ons.",
            "<strong>Online Advertising</strong>: We use third-party ad services (e.g., Facebook, Google) for targeted ads. We may share aggregate, non-identifiable data with them."
          ]
        }
      ],
    },
    {
      id: "use-of-information",
      title: "Use of Your Information",
      icon: User,
      content: [
        {
          subtitle: "Purpose",
          description: "We use your Information for the following purposes:",
          bullets: [
            "Providing and improving our Services",
            "Developing new products, services, and features",
            "Analyzing trends, traffic, and usage",
            "Learning more about users via analytics",
            "Communicating with you",
            "Troubleshooting and support",
            "Fraud prevention and security",
            "Updating Services based on feedback",
            "Contacting you for service, product knowledge, and promotional offers (even if registered under DND/DNC/NCPR, for 180 days after registration)"
          ]
        }
      ],
    },
    {
      id: "sharing-information",
      title: "Sharing Your Information",
      icon: Globe,
      content: [
        {
          subtitle: "Sharing Entities",
          description: "We may share your Information with:",
          bullets: [
            "Mentors, other users, companies running promotions/surveys, advertising companies",
            "For security, legal compliance, or corporate restructuring",
            "Aggregated/de-identified or with your consent",
            "With service providers, contractors, and agents (e.g., payment, analytics, marketing, support)",
            "With business partners and for promotions/surveys",
            "For legal, security, or compliance reasons",
            "During a change in control (e.g., merger, acquisition)",
            "Within our corporate family"
          ]
        }
      ],
    },
    {
      id: "data-security",
      title: "Data Security",
      icon: Shield,
      content: [
        {
          subtitle: "Security Measures",
          description: "We use appropriate security based on the type and sensitivity of Information being stored. There is always a risk of unauthorized access with internet-enabled platforms. Please protect your password and contact us if you suspect unauthorized access.",
          bullets: []
        }
      ],
    },
    {
      id: "information-review",
      title: "Information Review & Accuracy",
      icon: CheckCircle,
      content: [
        {
          subtitle: "Accuracy Responsibility",
          description: "Please review your Information periodically to ensure accuracy. We are not responsible for the authenticity of Information supplied by you. Discrepancies and grievances will be addressed within 30 days by our Grievance Officer (see Section 13).",
          bullets: []
        }
      ],
    },
    {
      id: "data-retention",
      title: "Data Retention",
      icon: Database,
      content: [
        {
          subtitle: "Retention Policy",
          description: "We do not retain Sensitive Personal Information longer than required. Public content may be retained indefinitely in cached/archived pages or if copied by others. We may retain Information for internal processing, analytics, fraud monitoring, or on an anonymized basis.",
          bullets: []
        }
      ],
    },
    {
      id: "your-rights",
      title: "Your Rights",
      icon: User,
      content: [
        {
          subtitle: "User Rights",
          description: "You have the following rights regarding your Information:",
          bullets: [
            "Opt out of promotional emails, cookies, and certain ad services",
            "Update or terminate your Account",
            "Request review, correction, or deletion of your Information",
            "Revoke consent (may affect your use of the Platform)",
            "Request deletion of your data (residual data may be retained in logs/backups for up to a year)",
            "Contact us at <a href=\"mailto:connect@codeunia.com\" className=\"text-blue-500 hover:underline\">connect@codeunia.com</a> for any rights requests. We require up to 30 days to comply."
          ]
        }
      ],
    },
    {
      id: "third-party-links",
      title: "Third-Party Links",
      icon: Globe,
      content: [
        {
          subtitle: "External Links",
          description: "Our Platform may contain links to third-party websites or apps. We are not responsible for their privacy policies. Please review their policies before submitting data.",
          bullets: []
        }
      ],
    },
    {
      id: "third-party-embeds",
      title: "Third-Party Embeds",
      icon: Globe,
      content: [
        {
          subtitle: "Embedded Content",
          description: "Some content on the Platform is hosted by third parties (e.g., YouTube videos). These embeds are governed by the third party's privacy policy, not ours. Be careful when submitting Information to third-party embeds.",
          bullets: []
        }
      ],
    },
    {
      id: "policy-changes",
      title: "Changes to Privacy Policy",
      icon: FileText,
      content: [
        {
          subtitle: "Policy Updates",
          description: "We may update this Privacy Policy periodically. We will post updates at this link and notify you of material changes. Continued use of the Services constitutes acceptance of the updated policy.",
          bullets: []
        }
      ],
    },
    {
      id: "disclaimer",
      title: "Disclaimer",
      icon: AlertTriangle,
      content: [
        {
          subtitle: "Security Disclaimer",
          description: "We follow best practices and take security measures to protect your Information, but cannot guarantee its security. Any transmission is at your own risk.",
          bullets: []
        }
      ],
    },
    {
      id: "communications",
      title: "Communications From Us",
      icon: Mail,
      content: [
        {
          subtitle: "Service Announcements",
          description: "We may send you service-related announcements (e.g., maintenance, security, privacy, or administrative communications) via SMS, email, push notifications, WhatsApp, or other channels. You may not opt out of these non-promotional communications.",
          bullets: []
        }
      ],
    },
    {
      id: "grievance-officer",
      title: "Grievance Officer",
      icon: Shield,
      content: [
        {
          subtitle: "Grievance Handling",
          description: "The Company has a Grievance Officer to address your concerns regarding data safety, privacy, discrepancies, and the usage of Platform. We will resolve issues within 30 days of receiving them.",
          bullets: [
            "Email: <a href=\"mailto:connect@codeunia.com\" className=\"text-blue-500 hover:underline\">connect@codeunia.com</a>"
          ]
        }
      ],
    },
    {
      id: "contact",
      title: "Contact Us",
      icon: Mail,
      content: [
        {
          subtitle: "Support Contact",
          description: "If you have any questions about this Privacy Policy, please contact us:",
          bullets: [
            "Email: <a href=\"mailto:connect@codeunia.com\" className=\"text-blue-500 hover:underline\">connect@codeunia.com</a>",
            "Website: <a href=\"https://codeunia.com\" className=\"text-blue-500 hover:underline\">codeunia.com</a>"
          ]
        }
      ],
    },
  ]

  return (
    <div className="flex flex-col overflow-hidden">
      <Header />
      {/* hero */}
      <section className="py-20 md:py-32 relative overflow-hidden">
        <div
          className={cn(
            "absolute inset-0",
            "[background-size:20px_20px]",
            "[background-image:linear-gradient(to_right,rgba(99,102,241,0.8)_1px,transparent_1px),linear-gradient(to_bottom,rgba(99,102,241,0.8)_1px,transparent_1px)]",
            "dark:[background-image:linear-gradient(to_right,rgba(139,92,246,0.8)_1px,transparent_1px),linear-gradient(to_bottom,rgba(139,92,246,0.8)_1px,transparent_1px)]",
          )}
        />
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center bg-background [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"></div>
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-background to-purple-500/5 animate-gradient"></div>
        <div className="absolute inset-0">
          <div className="absolute top-20 left-10 w-72 h-72 bg-primary/10 rounded-full blur-3xl animate-pulse-slow"></div>
          <div
            className="absolute bottom-20 right-10 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse-slow"
            style={{ animationDelay: "2s" }}
          ></div>
        </div>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="container px-4 mx-auto relative z-10"
        >
          <div className="max-w-4xl mx-auto text-center space-y-8">
            <motion.div
              initial={{ scale: 0.9 }}
              animate={{ scale: 1 }}
              transition={{ duration: 0.3 }}
            >
              <div className="flex flex-col items-center justify-center gap-4">
                <button className="bg-slate-800 no-underline group relative shadow-2xl shadow-zinc-900 rounded-full p-px text-sm font-semibold leading-6 text-white inline-block cursor-default">
                  <span className="absolute inset-0 overflow-hidden rounded-full">
                    <span className="absolute inset-0 rounded-full bg-[image:radial-gradient(75%_100%_at_50%_0%,rgba(56,189,248,0.6)_0%,rgba(56,189,248,0)_75%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
                  </span>
                  <div className="relative flex space-x-2 items-center z-10 rounded-full bg-zinc-950 py-1 px-4 ring-1 ring-white/10">
                    <span>Privacy Policy</span>
                  </div>
                  <span className="absolute -bottom-0 left-[1.125rem] h-px w-[calc(100%-2.25rem)] bg-gradient-to-r from-emerald-400/0 via-emerald-400/90 to-emerald-400/0 transition-opacity duration-500 group-hover:opacity-40" />
                </button>
              </div>
            </motion.div>
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="text-5xl md:text-6xl font-bold tracking-tight leading-tight"
            >
              Privacy {" "}
              <motion.span
                className="gradient-text inline-block"
                animate={{
                  backgroundPosition: ["0% 50%", "100% 50%", "0% 50%"],
                }}
                transition={{
                  duration: 4,
                  repeat: Infinity,
                  ease: "linear"
                }}
                style={{
                  background: "linear-gradient(90deg, #6366f1, #8b5cf6, #06b6d4, #6366f1)",
                  backgroundSize: "300% 100%",
                  WebkitBackgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                }}
              >
                Policy
              </motion.span>
            </motion.h1>
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
              className="text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto leading-relaxed"
            >
              Please read this Privacy Policy carefully before using Codeunia. By using our platform, you agree to the collection and use of your information as described.
            </motion.p>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.4 }}
              className="flex items-center justify-center space-x-2 text-sm text-muted-foreground"
            >
              <Calendar className="h-4 w-4" />
              <span>Last updated: {lastUpdated}</span>
            </motion.div>
          </div>
        </motion.div>
      </section>
      {/* Intro Paragraph Section */}
      <section className="py-12 bg-gradient-to-b from-muted/30 to-background">
        <div className="container px-4 mx-auto">
          <div className="max-w-4xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              viewport={{ once: true }}
            >
              <Card className="border-0 shadow-lg bg-gradient-to-br from-primary/5 via-background to-purple-500/5 dark:from-primary/10 dark:via-background dark:to-purple-500/10 hover:shadow-xl transition-all duration-300 backdrop-blur-sm">
                <CardContent className="pt-6">
                  <p className="text-muted-foreground leading-relaxed">
                    We use your Information for providing and improving the Services. By using the Services, you agree to the collection and use of Information in accordance with this Privacy Policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible on the website. We will not use or share your Information with anyone except as described in this Privacy Policy.
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          </div>
        </div>
      </section>

      {/* main content section */}
      <section className="py-20">
        <div className="container px-4 mx-auto">
          <div className="max-w-4xl mx-auto space-y-12">
            {sections.map((section, index) => (
              <motion.div
                key={section.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
              >
                <Card className="border-0 shadow-lg card-hover hover:shadow-xl transition-all duration-300">
                  <CardHeader>
                    <div className="flex items-center space-x-4">
                      <div className="w-14 h-14 bg-gradient-to-br from-primary to-purple-600 rounded-2xl flex items-center justify-center shadow-lg">
                        <section.icon className="h-7 w-7 text-white" />
                      </div>
                      <div>
                        <CardTitle className="text-2xl">{section.title}</CardTitle>
                        <p className="text-sm text-muted-foreground">Section {index + 1}</p>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-6">
                      {section.content.map((item, itemIndex) => (
                        <motion.div
                          key={itemIndex}
                          initial={{ opacity: 0, x: -20 }}
                          whileInView={{ opacity: 1, x: 0 }}
                          transition={{ duration: 0.5, delay: itemIndex * 0.1 }}
                          viewport={{ once: true }}
                          className="space-y-2"
                        >
                          <h4 className="text-lg font-semibold text-primary">{item.subtitle}</h4>
                          {item.description && (
                            <p className="text-muted-foreground leading-relaxed mb-4" dangerouslySetInnerHTML={{ __html: item.description }} />
                          )}
                          {item.bullets && item.bullets.length > 0 && (
                            <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                              {item.bullets.map((bullet, bulletIndex) => (
                                <li key={bulletIndex} className="leading-relaxed" dangerouslySetInnerHTML={{ __html: bullet }} />
                              ))}
                            </ul>
                          )}
                          {itemIndex < section.content.length - 1 && <Separator className="mt-4" />}
                        </motion.div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
      {/* contact section */}
      <section className="py-20 bg-gradient-to-b from-muted/30 to-background">
        <div className="container px-4 mx-auto">
          <div className="max-w-4xl mx-auto space-y-8">
            <div className="text-center space-y-6">
              <motion.div
                initial={{ scale: 0.9 }}
                animate={{ scale: 1 }}
                transition={{ duration: 0.3 }}
              >
                <div className="flex flex-col items-center justify-center gap-4">
                  <button className="bg-slate-800 no-underline group relative shadow-2xl shadow-zinc-900 rounded-full p-px text-sm font-semibold leading-6 text-white inline-block cursor-default">
                    <span className="absolute inset-0 overflow-hidden rounded-full">
                      <span className="absolute inset-0 rounded-full bg-[image:radial-gradient(75%_100%_at_50%_0%,rgba(56,189,248,0.6)_0%,rgba(56,189,248,0)_75%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
                    </span>
                    <div className="relative flex space-x-2 items-center z-10 rounded-full bg-zinc-950 py-1 px-4 ring-1 ring-white/10">
                      <span>Get in Touch</span>
                    </div>
                    <span className="absolute -bottom-0 left-[1.125rem] h-px w-[calc(100%-2.25rem)] bg-gradient-to-r from-emerald-400/0 via-emerald-400/90 to-emerald-400/0 transition-opacity duration-500 group-hover:opacity-40" />
                  </button>
                </div>
              </motion.div>
              <motion.h1
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.2 }}
                className="text-5xl md:text-6xl font-bold tracking-tight leading-tight"
              >
                Questions About {" "}
                <motion.span
                  className="gradient-text inline-block"
                  animate={{
                    backgroundPosition: ["0% 50%", "100% 50%", "0% 50%"],
                  }}
                  transition={{
                    duration: 4,
                    repeat: Infinity,
                    ease: "linear"
                  }}
                  style={{
                    background: "linear-gradient(90deg, #6366f1, #8b5cf6, #06b6d4, #6366f1)",
                    backgroundSize: "300% 100%",
                    WebkitBackgroundClip: "text",
                    WebkitTextFillColor: "transparent",
                  }}
                >
                  Privacy?
                </motion.span>
              </motion.h1>
              <p className="text-xl text-muted-foreground">
                We&apos;re here to help you understand our privacy policy.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <Card className="border-0 shadow-lg card-hover">
                <CardHeader>
                  <div className="flex items-center space-x-3">
                    <Mail className="h-8 w-8 text-primary" />
                    <CardTitle className="text-xl">Contact Our Team</CardTitle>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <p className="text-muted-foreground">
                    Have questions about this privacy policy or need clarification? Our team is here to help.
                  </p>
                  <Button className="w-full glow-effect hover:scale-105 transition-all duration-300">
                    Email Support
                  </Button>
                </CardContent>
              </Card>
              <Card className="border-0 shadow-lg card-hover">
                <CardHeader>
                  <div className="flex items-center space-x-3">
                    <AlertTriangle className="h-8 w-8 text-primary" />
                    <CardTitle className="text-xl">Report Privacy Concerns</CardTitle>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <p className="text-muted-foreground">
                    If you have concerns about your data or privacy, please report them to us immediately.
                  </p>
                  <Button variant="outline" className="w-full hover:scale-105 transition-all duration-300">
                    Report Issue
                  </Button>
                </CardContent>
              </Card>
            </div>
            <Card className="border-0 shadow-lg bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-950/20 dark:to-pink-950/20">
              <CardHeader>
                <div className="flex items-center space-x-3">
                  <FileText className="h-8 w-8 text-primary" />
                  <CardTitle className="text-xl">Privacy Policy Updates</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground leading-relaxed">
                  We may update this Privacy Policy from time to time to reflect changes in our services or legal requirements.
                  We will notify you of any material changes by posting the new policy on this page and updating the
                  &quot;Last updated&quot; date. We encourage you to review this policy periodically to stay informed about
                  how we protect your information.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
      {/* cta */}
      <section className="py-24 relative overflow-hidden bg-gradient-to-br from-primary/10 via-purple-500/10 to-background dark:from-primary/20 dark:via-purple-500/20 dark:to-background">
        <div className="absolute inset-0">
          <div className="absolute top-10 left-10 w-32 h-32 bg-primary/20 dark:bg-primary/30 rounded-full blur-xl animate-float"></div>
          <div
            className="absolute bottom-10 right-10 w-48 h-48 bg-purple-500/20 dark:bg-purple-500/30 rounded-full blur-xl animate-float"
            style={{ animationDelay: "3s" }}
          ></div>
        </div>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
          className="container px-4 mx-auto text-center relative z-10"
        >
          <div className="max-w-3xl mx-auto space-y-8 p-8 rounded-3xl bg-background/50 dark:bg-background/80 backdrop-blur-md border border-primary/10 dark:border-primary/20 shadow-xl">
            <motion.div
              initial={{ scale: 0.9 }}
              animate={{ scale: 1 }}
              transition={{ duration: 0.3 }}
            >
              <div className="flex flex-col items-center justify-center gap-4">
                <button className="bg-slate-800 no-underline group relative shadow-2xl shadow-zinc-900 rounded-full p-px text-sm font-semibold leading-6 text-white inline-block cursor-default">
                  <span className="absolute inset-0 overflow-hidden rounded-full">
                    <span className="absolute inset-0 rounded-full bg-[image:radial-gradient(75%_100%_at_50%_0%,rgba(56,189,248,0.6)_0%,rgba(56,189,248,0)_75%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
                  </span>
                  <div className="relative flex space-x-2 items-center z-10 rounded-full bg-zinc-950 py-1 px-4 ring-1 ring-white/10">
                    <span>📜 Ready to Get Started?</span>
                  </div>
                  <span className="absolute -bottom-0 left-[1.125rem] h-px w-[calc(100%-2.25rem)] bg-gradient-to-r from-emerald-400/0 via-emerald-400/90 to-emerald-400/0 transition-opacity duration-500 group-hover:opacity-40" />
                </button>
              </div>
            </motion.div>
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="text-5xl md:text-6xl font-bold tracking-tight leading-tight"
            >
              Join Codeunia {" "}
              <motion.span
                className="gradient-text inline-block"
                animate={{
                  backgroundPosition: ["0% 50%", "100% 50%", "0% 50%"],
                }}
                transition={{
                  duration: 4,
                  repeat: Infinity,
                  ease: "linear"
                }}
                style={{
                  background: "linear-gradient(90deg, #6366f1, #8b5cf6, #06b6d4, #6366f1)",
                  backgroundSize: "300% 100%",
                  WebkitBackgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                }}
              >
                Today
              </motion.span>
            </motion.h1>
            <p className="text-xl text-muted-foreground dark:text-muted-foreground/90 leading-relaxed">
              Start your coding journey with a platform that values your privacy and transparency.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button
                size="lg"
                variant="default"
                className="px-8 py-6 text-lg font-semibold hover:scale-105 transition-all duration-300"
              >
                Create Account
              </Button>
              <Button
                size="lg"
                variant="outline"
                className="px-8 py-6 text-lg font-semibold hover:scale-105 transition-transform duration-300"
              >
                Learn More
              </Button>
            </div>
          </div>
        </motion.div>
      </section>
      <Footer />
    </div>
  )
}