-- Create reserved_usernames table
CREATE TABLE IF NOT EXISTS reserved_usernames (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  category VARCHAR(50) NOT NULL CHECK (
    category IN (
      'system', 'admin', 'api', 'events', 'learning', 'professional', 
      'content', 'legal', 'ecommerce', 'discovery', 'premium', 'community', 
      'brand', 'common_words', 'single_letters', 'abbreviations', 'error_pages'
    )
  ),
  reason TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id),
  expires_at TIMESTAMP WITH TIME ZONE
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_reserved_usernames_username ON reserved_usernames (username);
CREATE INDEX IF NOT EXISTS idx_reserved_usernames_category ON reserved_usernames (category);
CREATE INDEX IF NOT EXISTS idx_reserved_usernames_active ON reserved_usernames (is_active);
CREATE INDEX IF NOT EXISTS idx_reserved_usernames_expires ON reserved_usernames (expires_at);

-- Add RLS (Row Level Security)
ALTER TABLE reserved_usernames ENABLE ROW LEVEL SECURITY;

-- Policy: Only admins can manage reserved usernames
CREATE POLICY "Admins can manage reserved usernames" ON reserved_usernames
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.is_admin = true
    )
  );

-- Policy: Anyone can read active reserved usernames
CREATE POLICY "Anyone can read active reserved usernames" ON reserved_usernames
  FOR SELECT USING (is_active = true);

-- Insert initial reserved usernames
INSERT INTO reserved_usernames (username, category, reason) VALUES
-- System & Admin
('admin', 'admin', 'Reserved for system administrators'),
('root', 'admin', 'Reserved for system administrators'),
('superadmin', 'admin', 'Reserved for system administrators'),
('moderator', 'admin', 'Reserved for system moderators'),
('staff', 'admin', 'Reserved for staff members'),
('login', 'system', 'Conflicts with authentication routes'),
('logout', 'system', 'Conflicts with authentication routes'),
('signup', 'system', 'Conflicts with authentication routes'),
('register', 'system', 'Conflicts with authentication routes'),
('auth', 'system', 'Conflicts with authentication routes'),
('profile', 'system', 'Conflicts with profile routes'),
('user', 'system', 'Conflicts with user routes'),
('account', 'system', 'Conflicts with account routes'),
('settings', 'system', 'Conflicts with settings routes'),
('dashboard', 'system', 'Conflicts with dashboard routes'),
('home', 'system', 'Conflicts with home route'),
('welcome', 'system', 'Conflicts with welcome route'),
('me', 'system', 'Conflicts with user routes'),
('my', 'system', 'Conflicts with user routes'),
('self', 'system', 'Conflicts with user routes'),

-- API & Technical
('api', 'api', 'Conflicts with API routes'),
('v1', 'api', 'Conflicts with API version routes'),
('v2', 'api', 'Conflicts with API version routes'),
('v3', 'api', 'Conflicts with API version routes'),
('assets', 'api', 'Conflicts with static assets routes'),
('cdn', 'api', 'Conflicts with CDN routes'),
('static', 'api', 'Conflicts with static files routes'),
('backend', 'api', 'Conflicts with backend routes'),
('database', 'api', 'Conflicts with database routes'),
('server', 'api', 'Conflicts with server routes'),
('config', 'api', 'Conflicts with configuration routes'),
('system', 'api', 'Conflicts with system routes'),
('www', 'api', 'Conflicts with web routes'),
('mail', 'api', 'Conflicts with mail routes'),
('ftp', 'api', 'Conflicts with FTP routes'),
('smtp', 'api', 'Conflicts with SMTP routes'),
('pop', 'api', 'Conflicts with POP routes'),
('imap', 'api', 'Conflicts with IMAP routes'),

-- Events & Activities
('events', 'events', 'Conflicts with events routes'),
('event', 'events', 'Conflicts with event routes'),
('join', 'events', 'Conflicts with join routes'),
('participate', 'events', 'Conflicts with participation routes'),
('register', 'events', 'Conflicts with registration routes'),
('hackathon', 'events', 'Conflicts with hackathon routes'),
('contest', 'events', 'Conflicts with contest routes'),
('quiz', 'events', 'Conflicts with quiz routes'),
('project', 'events', 'Conflicts with project routes'),
('challenge', 'events', 'Conflicts with challenge routes'),
('leaderboard', 'events', 'Conflicts with leaderboard routes'),
('rank', 'events', 'Conflicts with ranking routes'),
('score', 'events', 'Conflicts with scoring routes'),
('points', 'events', 'Conflicts with points routes'),
('achievements', 'events', 'Conflicts with achievements routes'),

-- Learning & Education
('learn', 'learning', 'Conflicts with learning routes'),
('learning', 'learning', 'Conflicts with learning routes'),
('academy', 'learning', 'Conflicts with academy routes'),
('course', 'learning', 'Conflicts with course routes'),
('module', 'learning', 'Conflicts with module routes'),
('tutorial', 'learning', 'Conflicts with tutorial routes'),
('guide', 'learning', 'Conflicts with guide routes'),
('help', 'learning', 'Conflicts with help routes'),
('support', 'learning', 'Conflicts with support routes'),
('documentation', 'learning', 'Conflicts with documentation routes'),
('school', 'learning', 'Conflicts with school routes'),
('university', 'learning', 'Conflicts with university routes'),
('college', 'learning', 'Conflicts with college routes'),
('institute', 'learning', 'Conflicts with institute routes'),

-- Professional Tools
('resume', 'professional', 'Conflicts with resume routes'),
('resumebuilder', 'professional', 'Conflicts with resume builder routes'),
('cv', 'professional', 'Conflicts with CV routes'),
('cvbuilder', 'professional', 'Conflicts with CV builder routes'),
('portfolio', 'professional', 'Conflicts with portfolio routes'),
('buildunia', 'professional', 'Reserved for BuildUnia product'),
('profileunia', 'professional', 'Reserved for ProfileUnia product'),
('certifyunia', 'professional', 'Reserved for CertifyUnia product'),
('badgeunia', 'professional', 'Reserved for BadgeUnia product'),
('job', 'professional', 'Conflicts with job routes'),
('career', 'professional', 'Conflicts with career routes'),
('hire', 'professional', 'Conflicts with hiring routes'),
('recruit', 'professional', 'Conflicts with recruitment routes'),
('apply', 'professional', 'Conflicts with application routes'),

-- Content & Media
('blog', 'content', 'Conflicts with blog routes'),
('blogs', 'content', 'Conflicts with blogs routes'),
('article', 'content', 'Conflicts with article routes'),
('news', 'content', 'Conflicts with news routes'),
('updates', 'content', 'Conflicts with updates routes'),
('press', 'content', 'Conflicts with press routes'),
('media', 'content', 'Conflicts with media routes'),
('image', 'content', 'Conflicts with image routes'),
('video', 'content', 'Conflicts with video routes'),
('photo', 'content', 'Conflicts with photo routes'),
('gallery', 'content', 'Conflicts with gallery routes'),
('post', 'content', 'Conflicts with post routes'),
('comment', 'content', 'Conflicts with comment routes'),
('reply', 'content', 'Conflicts with reply routes'),
('share', 'content', 'Conflicts with share routes'),

-- Legal & Policy
('about', 'legal', 'Conflicts with about route'),
('contact', 'legal', 'Conflicts with contact route'),
('support', 'legal', 'Conflicts with support route'),
('help', 'legal', 'Conflicts with help route'),
('faq', 'legal', 'Conflicts with FAQ route'),
('terms', 'legal', 'Conflicts with terms route'),
('privacy', 'legal', 'Conflicts with privacy route'),
('policy', 'legal', 'Conflicts with policy route'),
('cookies', 'legal', 'Conflicts with cookies route'),
('legal', 'legal', 'Conflicts with legal route'),
('disclaimer', 'legal', 'Conflicts with disclaimer route'),
('copyright', 'legal', 'Conflicts with copyright route'),
('trademark', 'legal', 'Conflicts with trademark route'),

-- E-commerce
('store', 'ecommerce', 'Conflicts with store routes'),
('shop', 'ecommerce', 'Conflicts with shop routes'),
('buy', 'ecommerce', 'Conflicts with buy routes'),
('cart', 'ecommerce', 'Conflicts with cart routes'),
('checkout', 'ecommerce', 'Conflicts with checkout routes'),
('payment', 'ecommerce', 'Conflicts with payment routes'),
('order', 'ecommerce', 'Conflicts with order routes'),
('purchase', 'ecommerce', 'Conflicts with purchase routes'),
('billing', 'ecommerce', 'Conflicts with billing routes'),
('invoice', 'ecommerce', 'Conflicts with invoice routes'),
('receipt', 'ecommerce', 'Conflicts with receipt routes'),
('product', 'ecommerce', 'Conflicts with product routes'),
('service', 'ecommerce', 'Conflicts with service routes'),
('pricing', 'ecommerce', 'Conflicts with pricing routes'),
('plans', 'ecommerce', 'Conflicts with plans routes'),

-- Discovery & Search
('explore', 'discovery', 'Conflicts with explore routes'),
('search', 'discovery', 'Conflicts with search routes'),
('discover', 'discovery', 'Conflicts with discover routes'),
('filter', 'discovery', 'Conflicts with filter routes'),
('trending', 'discovery', 'Conflicts with trending routes'),
('popular', 'discovery', 'Conflicts with popular routes'),
('featured', 'discovery', 'Conflicts with featured routes'),
('recommended', 'discovery', 'Conflicts with recommended routes'),
('suggested', 'discovery', 'Conflicts with suggested routes'),
('browse', 'discovery', 'Conflicts with browse routes'),
('find', 'discovery', 'Conflicts with find routes'),
('lookup', 'discovery', 'Conflicts with lookup routes'),
('directory', 'discovery', 'Conflicts with directory routes'),

-- Premium & Status
('premium', 'premium', 'Reserved for premium features'),
('pro', 'premium', 'Reserved for pro features'),
('plus', 'premium', 'Reserved for plus features'),
('gold', 'premium', 'Reserved for gold features'),
('platinum', 'premium', 'Reserved for platinum features'),
('verified', 'premium', 'Reserved for verified accounts'),
('vip', 'premium', 'Reserved for VIP accounts'),
('elite', 'premium', 'Reserved for elite accounts'),
('exclusive', 'premium', 'Reserved for exclusive accounts'),
('special', 'premium', 'Reserved for special accounts'),
('featured', 'premium', 'Reserved for featured accounts'),
('sponsored', 'premium', 'Reserved for sponsored accounts'),
('partner', 'premium', 'Reserved for partner accounts'),
('official', 'premium', 'Reserved for official accounts'),

-- Community & Social
('team', 'community', 'Conflicts with team routes'),
('community', 'community', 'Conflicts with community routes'),
('members', 'community', 'Conflicts with members routes'),
('invite', 'community', 'Conflicts with invite routes'),
('refer', 'community', 'Conflicts with refer routes'),
('friends', 'community', 'Conflicts with friends routes'),
('followers', 'community', 'Conflicts with followers routes'),
('following', 'community', 'Conflicts with following routes'),
('network', 'community', 'Conflicts with network routes'),
('group', 'community', 'Conflicts with group routes'),
('club', 'community', 'Conflicts with club routes'),
('organization', 'community', 'Conflicts with organization routes'),
('association', 'community', 'Conflicts with association routes'),

-- Brand & Identity
('codeunia', 'brand', 'Reserved for Codeunia brand'),
('build', 'brand', 'Reserved for BuildUnia brand'),
('buildunia', 'brand', 'Reserved for BuildUnia brand'),
('code', 'brand', 'Reserved for code-related features'),
('coders', 'brand', 'Reserved for coders community'),
('student', 'brand', 'Reserved for student features'),
('hackers', 'brand', 'Reserved for hackers community'),
('dev', 'brand', 'Reserved for developers'),
('developer', 'brand', 'Reserved for developers'),
('creator', 'brand', 'Reserved for creators'),
('maker', 'brand', 'Reserved for makers'),
('programmer', 'brand', 'Reserved for programmers'),
('engineer', 'brand', 'Reserved for engineers'),
('designer', 'brand', 'Reserved for designers'),
('architect', 'brand', 'Reserved for architects'),

-- Common Words (most common ones)
('the', 'common_words', 'Common word that could cause confusion'),
('and', 'common_words', 'Common word that could cause confusion'),
('or', 'common_words', 'Common word that could cause confusion'),
('but', 'common_words', 'Common word that could cause confusion'),
('for', 'common_words', 'Common word that could cause confusion'),
('with', 'common_words', 'Common word that could cause confusion'),
('from', 'common_words', 'Common word that could cause confusion'),
('to', 'common_words', 'Common word that could cause confusion'),
('in', 'common_words', 'Common word that could cause confusion'),
('on', 'common_words', 'Common word that could cause confusion'),
('at', 'common_words', 'Common word that could cause confusion'),
('by', 'common_words', 'Common word that could cause confusion'),
('of', 'common_words', 'Common word that could cause confusion'),
('a', 'common_words', 'Common word that could cause confusion'),
('an', 'common_words', 'Common word that could cause confusion'),
('is', 'common_words', 'Common word that could cause confusion'),
('are', 'common_words', 'Common word that could cause confusion'),
('was', 'common_words', 'Common word that could cause confusion'),
('were', 'common_words', 'Common word that could cause confusion'),
('be', 'common_words', 'Common word that could cause confusion'),
('been', 'common_words', 'Common word that could cause confusion'),
('being', 'common_words', 'Common word that could cause confusion'),
('have', 'common_words', 'Common word that could cause confusion'),
('has', 'common_words', 'Common word that could cause confusion'),
('had', 'common_words', 'Common word that could cause confusion'),
('do', 'common_words', 'Common word that could cause confusion'),
('does', 'common_words', 'Common word that could cause confusion'),
('did', 'common_words', 'Common word that could cause confusion'),
('will', 'common_words', 'Common word that could cause confusion'),
('would', 'common_words', 'Common word that could cause confusion'),
('could', 'common_words', 'Common word that could cause confusion'),
('should', 'common_words', 'Common word that could cause confusion'),
('can', 'common_words', 'Common word that could cause confusion'),
('may', 'common_words', 'Common word that could cause confusion'),
('might', 'common_words', 'Common word that could cause confusion'),
('must', 'common_words', 'Common word that could cause confusion'),
('shall', 'common_words', 'Common word that could cause confusion'),

-- Single Letters
('a', 'single_letters', 'Single letter that could cause confusion'),
('b', 'single_letters', 'Single letter that could cause confusion'),
('c', 'single_letters', 'Single letter that could cause confusion'),
('d', 'single_letters', 'Single letter that could cause confusion'),
('e', 'single_letters', 'Single letter that could cause confusion'),
('f', 'single_letters', 'Single letter that could cause confusion'),
('g', 'single_letters', 'Single letter that could cause confusion'),
('h', 'single_letters', 'Single letter that could cause confusion'),
('i', 'single_letters', 'Single letter that could cause confusion'),
('j', 'single_letters', 'Single letter that could cause confusion'),
('k', 'single_letters', 'Single letter that could cause confusion'),
('l', 'single_letters', 'Single letter that could cause confusion'),
('m', 'single_letters', 'Single letter that could cause confusion'),
('n', 'single_letters', 'Single letter that could cause confusion'),
('o', 'single_letters', 'Single letter that could cause confusion'),
('p', 'single_letters', 'Single letter that could cause confusion'),
('q', 'single_letters', 'Single letter that could cause confusion'),
('r', 'single_letters', 'Single letter that could cause confusion'),
('s', 'single_letters', 'Single letter that could cause confusion'),
('t', 'single_letters', 'Single letter that could cause confusion'),
('u', 'single_letters', 'Single letter that could cause confusion'),
('v', 'single_letters', 'Single letter that could cause confusion'),
('w', 'single_letters', 'Single letter that could cause confusion'),
('x', 'single_letters', 'Single letter that could cause confusion'),
('y', 'single_letters', 'Single letter that could cause confusion'),
('z', 'single_letters', 'Single letter that could cause confusion'),

-- Common Abbreviations
('www', 'abbreviations', 'Common web abbreviation'),
('http', 'abbreviations', 'Common protocol abbreviation'),
('https', 'abbreviations', 'Common protocol abbreviation'),
('ftp', 'abbreviations', 'Common protocol abbreviation'),
('smtp', 'abbreviations', 'Common protocol abbreviation'),
('pop', 'abbreviations', 'Common protocol abbreviation'),
('imap', 'abbreviations', 'Common protocol abbreviation'),
('api', 'abbreviations', 'Common technical abbreviation'),
('sdk', 'abbreviations', 'Common technical abbreviation'),
('cli', 'abbreviations', 'Common technical abbreviation'),
('gui', 'abbreviations', 'Common technical abbreviation'),
('ui', 'abbreviations', 'Common technical abbreviation'),
('ux', 'abbreviations', 'Common technical abbreviation'),
('db', 'abbreviations', 'Common technical abbreviation'),
('sql', 'abbreviations', 'Common technical abbreviation'),
('js', 'abbreviations', 'Common programming language abbreviation'),
('ts', 'abbreviations', 'Common programming language abbreviation'),
('py', 'abbreviations', 'Common programming language abbreviation'),
('java', 'abbreviations', 'Common programming language abbreviation'),
('cpp', 'abbreviations', 'Common programming language abbreviation'),
('csharp', 'abbreviations', 'Common programming language abbreviation'),
('php', 'abbreviations', 'Common programming language abbreviation'),
('ruby', 'abbreviations', 'Common programming language abbreviation'),
('html', 'abbreviations', 'Common markup language abbreviation'),
('css', 'abbreviations', 'Common styling language abbreviation'),
('xml', 'abbreviations', 'Common markup language abbreviation'),
('json', 'abbreviations', 'Common data format abbreviation'),
('yaml', 'abbreviations', 'Common data format abbreviation'),
('toml', 'abbreviations', 'Common data format abbreviation'),

-- Error Pages & System
('404', 'error_pages', 'Conflicts with error page routes'),
('500', 'error_pages', 'Conflicts with error page routes'),
('error', 'error_pages', 'Conflicts with error page routes'),
('notfound', 'error_pages', 'Conflicts with not found routes'),
('forbidden', 'error_pages', 'Conflicts with forbidden routes'),
('unauthorized', 'error_pages', 'Conflicts with unauthorized routes'),
('maintenance', 'error_pages', 'Conflicts with maintenance routes'),
('down', 'error_pages', 'Conflicts with down page routes'),
('offline', 'error_pages', 'Conflicts with offline page routes'),
('status', 'error_pages', 'Conflicts with status page routes'),
('health', 'error_pages', 'Conflicts with health check routes'),
('ping', 'error_pages', 'Conflicts with ping routes'),
('pong', 'error_pages', 'Conflicts with pong routes'),
('echo', 'error_pages', 'Conflicts with echo routes'),
('test', 'error_pages', 'Conflicts with test routes'),
('debug', 'error_pages', 'Conflicts with debug routes'),
('log', 'error_pages', 'Conflicts with log routes')

ON CONFLICT (username) DO NOTHING; 